# Generated by Django 5.1.1 on 2024-09-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airlines", "0002_airport_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=64)),
                ("last", models.CharField(max_length=64)),
                (
                    "flights",
                    models.ManyToManyField(
                        related_name="passengers", to="airlines.flight"
                    ),
                ),
            ],
        ),
    ]
